# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - variamos-ms-security-requirements-autocomplete

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://variamos.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae49b1666ff2414282a28a6e9e4462fd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_16bdc716e3cc47b781f637395c3a3b9f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: variamos.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae49b1666ff2414282a28a6e9e4462fd }}/variamos/variamos_ms_security_requirements_autocomplete:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'variamos-ms-security-requirements-autocomplete'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_60349f4c00364f468e3a8b4ceed20447 }}
        images: 'variamos.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae49b1666ff2414282a28a6e9e4462fd }}/variamos/variamos_ms_security_requirements_autocomplete:${{ github.sha }}'